export default [
  {
    data: [
      'Pretoria1',
      'Pretoria2',
      'Pretoria3',
      'Pretoria4',
      'Pretoria5',
      'Pretoria6',
      'Pretoria7',
      'Pretoria8',
      'Pretoria9',
      'Pretoria10',
      'Pretoria11',
      'Pretoria12',
      'Pretoria13',
      'Pretoria14',
      'Pretoria15',
    ],
    title: 'Elon Musk #1',
    author: 'Pretoria',
    size: '100mb',
  },
  {
    data: [
      'Pretoria1',
      'Pretoria2',
      'Pretoria3',
      'Pretoria4',
      'Pretoria5',
      'Pretoria6',
      'Pretoria7',
      'Pretoria8',
      'Pretoria9',
      'Pretoria10',
      'Pretoria11',
      'Pretoria12',
      'Pretoria13',
      'Pretoria14',
      'Pretoria15',
    ],
    title: 'Elon Musk #1',
    author: 'Pretoria',
    size: '100mb',
  },
]
