export default [
  {
    data: [
      'pretoria1/Pretoria1',
      'pretoria1/Pretoria2',
      'pretoria1/Pretoria3',
      'pretoria1/Pretoria4',
      'pretoria1/Pretoria5',
      'pretoria1/Pretoria6',
      'pretoria1/Pretoria7',
      'pretoria1/Pretoria8',
      'pretoria1/Pretoria9',
      'pretoria1/Pretoria10',
      'pretoria1/Pretoria11',
      'pretoria1/Pretoria12',
      'pretoria1/Pretoria13',
      'pretoria1/Pretoria14',
      'pretoria1/Pretoria15',
      'pretoria1/Pretoria16',
      'pretoria1/Pretoria17',
      'pretoria1/Pretoria18',
      'pretoria1/Pretoria19',
      'pretoria1/Pretoria20',
      'pretoria1/Pretoria21',
      'pretoria1/Pretoria22',
      'pretoria1/Pretoria23',
    ],
    title: 'Elon Musk #1',
    author: 'Pretoria',
    identifier: 'pretoria1',
    size: '0.56 MB',
  },
  {
    data: [
      'pretoria2/Pretoria24',
      'pretoria2/Pretoria25',
      'pretoria2/Pretoria26',
      'pretoria2/Pretoria27',
      'pretoria2/Pretoria28',
      'pretoria2/Pretoria29',
      'pretoria2/Pretoria30',
      'pretoria2/Pretoria31',
      'pretoria2/Pretoria32',
      'pretoria2/Pretoria33',
      'pretoria2/Pretoria34',
      'pretoria2/Pretoria35',
      'pretoria2/Pretoria36',
      'pretoria2/Pretoria37',
      'pretoria2/Pretoria38',
      'pretoria2/Pretoria39',
      'pretoria2/Pretoria40',
      'pretoria2/Pretoria41',
      'pretoria2/Pretoria42',
      'pretoria2/Pretoria43',
      'pretoria2/Pretoria44',
      'pretoria2/Pretoria45',
      'pretoria2/Pretoria46',
    ],
    title: 'Elon Musk #2',
    author: 'Pretoria',
    identifier: 'pretoria2',
    size: '0.6 MB',
  },
  {
    data: [
      'muskElonMusk/MuskElonMusk1',
      'muskElonMusk/MuskElonMusk3',
      'muskElonMusk/MuskElonMusk4',
      'muskElonMusk/MuskElonMusk5',
      'muskElonMusk/MuskElonMusk6',
      'muskElonMusk/MuskElonMusk8',
      'muskElonMusk/MuskElonMusk9',
      'muskElonMusk/MuskElonMusk10',
      'muskElonMusk/MuskElonMusk11',
      'muskElonMusk/MuskElonMusk12',
      'muskElonMusk/MuskElonMusk13',
      'muskElonMusk/MuskElonMusk14',
      'muskElonMusk/MuskElonMusk15',
      'muskElonMusk/MuskElonMusk16',
      'muskElonMusk/MuskElonMusk18',
      'muskElonMusk/MuskElonMusk19',
      'muskElonMusk/MuskElonMusk21',
      'muskElonMusk/MuskElonMusk22',
      'muskElonMusk/MuskElonMusk23',
      'muskElonMusk/MuskElonMusk24',
      'muskElonMusk/MuskElonMusk25',
      'muskElonMusk/MuskElonMusk26',
      'muskElonMusk/MuskElonMusk27',
      'muskElonMusk/MuskElonMusk28',
      'muskElonMusk/MuskElonMusk29',
      'muskElonMusk/MuskElonMusk31',
      'muskElonMusk/MuskElonMusk32',
      'muskElonMusk/MuskElonMusk33',
      'muskElonMusk/MuskElonMusk37',
    ],
    title: 'Elon Musk #3',
    author: 'Alex Fo',
    identifier: 'muskElonMusk',
    size: '0.84 MB',
  },
  {
    data: [
      'starmanMusk/StarmanMusk1',
      'starmanMusk/StarmanMusk2',
      'starmanMusk/StarmanMusk3',
      'starmanMusk/StarmanMusk4',
      'starmanMusk/StarmanMusk5',
      'starmanMusk/StarmanMusk6',
      'starmanMusk/StarmanMusk7',
      'starmanMusk/StarmanMusk8',
      'starmanMusk/StarmanMusk9',
      'starmanMusk/StarmanMusk10',
      'starmanMusk/StarmanMusk11',
      'starmanMusk/StarmanMusk12',
      'starmanMusk/StarmanMusk13',
      'starmanMusk/StarmanMusk14',
      'starmanMusk/StarmanMusk15',
      'starmanMusk/StarmanMusk16',
      'starmanMusk/StarmanMusk17',
      'starmanMusk/StarmanMusk18',
      'starmanMusk/StarmanMusk19',
      'starmanMusk/StarmanMusk20',
      'starmanMusk/StarmanMusk21',
      'starmanMusk/StarmanMusk22',
      'starmanMusk/StarmanMusk23',
      'starmanMusk/StarmanMusk24',
      'starmanMusk/StarmanMusk25',
      'starmanMusk/StarmanMusk26',
      'starmanMusk/StarmanMusk27',
      'starmanMusk/StarmanMusk28',
      'starmanMusk/StarmanMusk30',
      'starmanMusk/StarmanMusk31',
    ],
    title: 'Starman Musk',
    author: 'Mari Inari',
    identifier: 'starmanMusk',
    size: '1.4 MB',
  },
]
